const GENRE_LABELS = {
  sf_history: 'Альтернативная история',
  sf_action: 'Боевая фантастика',
  sf_epic: 'Эпическая фантастика',
  sf_heroic: 'Героическая фантастика',
  sf_detective: 'Детективная фантастика',
  sf_cyberpunk: 'Киберпанк',
  sf_space: 'Космическая фантастика',
  sf_social: 'Социально-психологическая фантастика',
  sf_horror: 'Ужасы',
  sf_humor: 'Юмористическая фантастика',
  sf_fantasy: 'Фэнтези',
  sf: 'Научная Фантастика',
  sf_fantasy_city: 'Городское фэнтези',
  sf_postapocalyptic: 'Постапокалипсис',
  sf_litrpg: 'ЛитРПГ',
  sf_etc: 'Фантастика',
  russian_fantasy: 'Славянское фэнтези',
  sf_technofantasy: 'Технофэнтези',
  fairy_fantasy: 'Мифологическое фэнтези',
  hronoopera: 'Хроноопера',
  sf_mystic: 'Мистика',
  sf_stimpank: 'Стимпанк',
  modern_tale: 'Современная сказка',
  popadancy: 'Попаданцы',
  det_classic: 'Классический детектив',
  det_police: 'Полицейский детектив',
  det_action: 'Боевик',
  det_irony: 'Иронический детектив, дамский детективный роман',
  det_history: 'Исторический детектив',
  det_espionage: 'Шпионский детектив',
  det_crime: 'Криминальный детектив',
  det_political: 'Политический детектив',
  det_maniac: 'Про маньяков',
  det_hard: 'Крутой детектив',
  thriller: 'Триллер',
  detective: 'Детективы',
  det_su: 'Советский детектив',
  prose: 'Проза',
  prose_classic: 'Классическая проза',
  prose_history: 'Историческая проза',
  prose_contemporary: 'Современная русская и зарубежная проза',
  prose_counter: 'Контркультура',
  prose_rus_classic: 'Русская классическая проза',
  prose_su_classics: 'Советская классическая проза',
  prose_military: 'Проза о войне',
  foreign_prose: 'Зарубежная классическая проза',
  foreign_antique: 'Средневековая классическая проза',
  literature_18: 'Классическая проза XVII-XVIII веков',
  literature_19: 'Классическая проза XIX века',
  literature_20: 'Классическая проза XX века',
  gothic_novel: 'Готический роман',
  prose_magic: 'Магический реализм',
  epistolary_fiction: 'Эпистолярная проза',
  prose_neformatny: 'Экспериментальная, неформатная проза',
  aphorisms: 'Афоризмы, цитаты',
  great_story: 'Роман, повесть',
  story: 'Малые литературные формы прозы: рассказы, эссе, новеллы, феерия',
  prose_abs: 'Фантасмагория, абсурдистская проза',
  love_contemporary: 'Современные любовные романы',
  love_history: 'Исторические любовные романы',
  love_detective: 'Остросюжетные любовные романы',
  love_short: 'Короткие любовные романы',
  love_erotica: 'Эротическая литература',
  love: 'Любовные романы',
  love_sf: 'Любовное фэнтези, любовно-фантастические романы',
  love_hard: 'Порно',
  adv_history: 'Исторические приключения',
  adv_indian: 'Вестерн, про индейцев',
  adv_maritime: 'Морские приключения',
  adv_geo: 'Путешествия и география',
  adv_animal: 'Природа и животные',
  adventure: 'Приключения',
  child_adv: 'Приключения для детей и подростков',
  adv_modern: 'Приключения в современном мире',
  tale_chivalry: 'Рыцарский роман',
  adv_story: 'Авантюрный роман',
  child_tale: 'Сказки народов мира',
  child_verse: 'Стихи для детей',
  child_prose: 'Проза для детей',
  child_sf: 'Фантастика для детей',
  child_det: 'Детская остросюжетная литература',
  child_education: 'Детская образовательная литература',
  children: 'Детская литература',
  child_classical: 'Классическая детская литература',
  child_tale_rus: 'Русские сказки',
  foreign_children: 'Зарубежная литература для детей',
  prose_game: 'Игры, упражнения для детей',
  religion_budda: 'Буддизм',
  sci_religion: 'Религиоведение',
  religion_esoterics: 'Эзотерика, эзотерическая литература',
  religion_self: 'Самосовершенствование',
  religion: 'Религия, религиозная литература',
  religion_christianity: 'Христианство',
  religion_orthodoxy: 'Православие',
  religion_protestantism: 'Протестантизм',
  religion_catholicism: 'Католицизм',
  religion_judaism: 'Иудаизм',
  religion_hinduism: 'Индуизм',
  religion_islam: 'Ислам',
  religion_paganism: 'Язычество',
  astrology: 'Астрология и хиромантия',
  poetry: 'Поэзия',
  humor_verse: 'Юмористические стихи, басни',
  poetry_classical: 'Классическая поэзия',
  poetry_modern: 'Современная поэзия',
  poetry_rus_classical: 'Классическая русская поэзия',
  poetry_rus_modern: 'Современная русская поэзия',
  poetry_for_classical: 'Классическая зарубежная поэзия',
  poetry_for_modern: 'Современная зарубежная поэзия',
  poetry_east: 'Поэзия Востока',
  lyrics: 'Лирика',
  song_poetry: 'Песенная поэзия',
  poem: 'Поэма, эпическая поэзия',
  palindromes: 'Визуальная и экспериментальная поэзия, верлибры, палиндромы',
  dramaturgy: 'Драматургия',
  comedy: 'Комедия',
  tragedy: 'Трагедия',
  drama: 'Драма',
  drama_antique: 'Античная драма',
  screenplays: 'Сценарий',
  vaudeville: 'Мистерия, буффонада, водевиль',
  antique_ant: 'Античная литература',
  antique_european: 'Европейская старинная литература',
  antique_russian: 'Древнерусская литература',
  antique_east: 'Древневосточная литература',
  antique: 'Старинная литература',
  antique_myths: 'Мифы. Легенды. Эпос',
  folklore: 'Фольклор, загадки',
  folk_tale: 'Народные сказки',
  epic: 'Былины, эпопея',
  proverbs: 'Пословицы, поговорки',
  folk_songs: 'Народные песни',
  child_folklore: 'Детский фольклор',
  limerick: 'Частушки, прибаутки, потешки',
  sci_history: 'История',
  sci_psychology: 'Психология и психотерапия',
  sci_philosophy: 'Философия',
  sci_politics: 'Политика',
  sci_juris: 'Юриспруденция',
  sci_linguistic: 'Языкознание, иностранные языки',
  sci_medicine: 'Медицина',
  sci_phys: 'Физика',
  sci_math: 'Математика',
  sci_chem: 'Химия',
  sci_biology: 'Биология, биофизика, биохимия',
  science: 'Научная литература',
  sci_cosmos: 'Астрономия и Космос',
  sci_geo: 'Геология и география',
  sci_state: 'Государство и право',
  sci_economy: 'Экономика',
  sci_medicine_alternative: 'Альтернативная медицина',
  sci_philology: 'Литературоведение',
  sci_popular: 'Зарубежная образовательная литература, зарубежная прикладная, научно-популярная литература',
  military_history: 'Военная история',
  sci_social_studies: 'Обществознание, социология',
  sci_zoo: 'Зоология',
  sci_botany: 'Ботаника',
  sci_ecology: 'Экология',
  sci_oriental: 'Востоковедение',
  sci_theories: 'Альтернативные науки и научные теории',
  sci_veterinary: 'Ветеринария',
  sci_culture: 'Культурология',
  notes: 'Партитуры',
  nonf_criticism: 'Критика',
  design: 'Искусство и Дизайн',
  music: 'Музыка',
  painting: 'Живопись, альбомы, иллюстрированные каталоги',
  architecture_book: 'Скульптура и архитектура',
  art_world_culture: 'Мировая художественная культура',
  cine: 'Кино',
  theatre: 'Театр',
  art_criticism: 'Искусствоведение',
  sci_tech: 'Технические науки',
  sci_build: 'Строительство и сопромат',
  sci_radio: 'Радиоэлектроника',
  sci_metal: 'Металлургия',
  sci_transport: 'Транспорт и авиация',
  military_weapon: 'Военное дело, военная техника и вооружение',
  auto_business: 'Автодело',
  equ_history: 'История техники',
  comp_www: 'ОС и Сети, интернет',
  comp_hard: 'Компьютерное железо и цифровая обработка сигналов',
  comp_db: 'Программирование, программы, базы данных',
  computers: 'Зарубежная компьютерная литература',
  tbg_computers: 'Учебные пособия, самоучители',
  ref_encyc: 'Энциклопедии',
  ref_dict: 'Словари',
  ref_ref: 'Справочники',
  ref_guide: 'Руководства',
  reference: 'Справочная литература',
  geo_guides: 'Путеводители, карты, атласы',
  nonf_biography: 'Биографии и Мемуары',
  nonf_publicism: 'Публицистика',
  nonfiction: 'Документальная литература',
  nonf_military: 'Военная документалистика и аналитика',
  military_special: 'Военное дело',
  travel_notes: 'География, путевые заметки',
  humor_anecdote: 'Анекдоты',
  humor_prose: 'Юмористическая проза',
  humor: 'Юмор',
  humor_satire: 'Сатира',
  home_cooking: 'Кулинария',
  home_pets: 'Домашние животные',
  home_crafts: 'Хобби и ремесла',
  home_entertain: 'Развлечения',
  home_health: 'Здоровье',
  home_garden: 'Сад и огород',
  home_diy: 'Сделай сам',
  home_sport: 'Боевые искусства, спорт',
  home_sex: 'Семейные отношения, секс',
  home: 'Домоводство',
  sci_pedagogy: 'Педагогика, воспитание детей, литература для родителей',
  auto_regulations: 'Автомобили и ПДД',
  home_collecting: 'Коллекционирование',
  family: 'Семейные отношения',
  other: 'Неотсортированное',
  periodic: 'Журналы, газеты',
  comics: 'Комиксы',
  unfinished: 'Незавершенное',
  fanfiction: 'Фанфик',
  network_literature: 'Самиздат, сетевая литература',
  banking: 'Финансы',
  org_behavior: 'Маркетинг, PR',
  popular_business: 'Карьера, кадры',
  economics_ref: 'Деловая литература',
  economics: 'Экономика',
  sci_textbook: 'Учебники и пособия',
  tbg_school: 'Школьные учебники и пособия, рефераты, шпаргалки',
  tbg_secondary: 'Учебники и пособия для среднего и специального образования',
  tbg_higher: 'Учебники и пособия ВУЗов'
};

export function formatGenreLabel(value = '') {
  const raw = String(value || '').trim();
  if (!raw) {
    return '';
  }
  return GENRE_LABELS[raw] || raw;
}

/** Сырые коды жанров из поля книги (разделители как в .inpx) */
export function parseGenreCodes(value = '') {
  return String(value || '')
    .split(/[:,;]/)
    .map((item) => item.trim())
    .filter(Boolean);
}

export function formatGenreList(value = '') {
  return parseGenreCodes(value).map((code) => formatGenreLabel(code));
}

export function formatAuthorLabel(value = '') {
  const raw = String(value || '').trim();
  if (!raw) {
    return '';
  }
  const authors = raw
    .split(':')
    .map((author) => author.split(',').map((part) => part.trim()).filter(Boolean).join(' '))
    .filter(Boolean);
  if (!authors.length) {
    return raw;
  }
  return authors.slice(0, 3).join(', ') + (authors.length > 3 ? ` и ещё ${authors.length - 3}` : '');
}

export function formatLanguageLabel(value = '') {
  const raw = String(value || '').trim();
  if (!raw || raw === 'unknown') {
    return 'Не указан';
  }
  return raw.toUpperCase();
}

export { GENRE_LABELS };
