const GENRE_LABELS = {
  sf_history: 'Альтернативная история',
  sf_action: 'Боевая фантастика',
  sf_epic: 'Эпическая фантастика',
  sf_heroic: 'Героическая фантастика',
  sf_detective: 'Детективная фантастика',
  sf_cyberpunk: 'Киберпанк',
  sf_space: 'Космическая фантастика',
  sf_social: 'Социально-психологическая фантастика',
  sf_horror: 'Ужасы',
  sf_humor: 'Юмористическая фантастика',
  sf_fantasy: 'Фэнтези',
  sf: 'Научная Фантастика',
  sf_fantasy_city: 'Городское фэнтези',
  sf_postapocalyptic: 'Постапокалипсис',
  sf_litrpg: 'ЛитРПГ',
  sf_etc: 'Фантастика',
  russian_fantasy: 'Славянское фэнтези',
  sf_technofantasy: 'Технофэнтези',
  fairy_fantasy: 'Мифологическое фэнтези',
  hronoopera: 'Хроноопера',
  sf_mystic: 'Мистика',
  sf_stimpank: 'Стимпанк',
  modern_tale: 'Современная сказка',
  popadancy: 'Попаданцы',
  det_classic: 'Классический детектив',
  det_police: 'Полицейский детектив',
  det_action: 'Боевик',
  det_irony: 'Иронический детектив, дамский детективный роман',
  det_history: 'Исторический детектив',
  det_espionage: 'Шпионский детектив',
  det_crime: 'Криминальный детектив',
  det_political: 'Политический детектив',
  det_maniac: 'Про маньяков',
  det_hard: 'Крутой детектив',
  thriller: 'Триллер',
  detective: 'Детективы',
  det_su: 'Советский детектив',
  prose: 'Проза',
  prose_classic: 'Классическая проза',
  prose_history: 'Историческая проза',
  prose_contemporary: 'Современная русская и зарубежная проза',
  prose_counter: 'Контркультура',
  prose_rus_classic: 'Русская классическая проза',
  prose_su_classics: 'Советская классическая проза',
  prose_military: 'Проза о войне',
  foreign_prose: 'Зарубежная классическая проза',
  foreign_antique: 'Средневековая классическая проза',
  literature_18: 'Классическая проза XVII-XVIII веков',
  literature_19: 'Классическая проза XIX века',
  literature_20: 'Классическая проза XX века',
  gothic_novel: 'Готический роман',
  prose_magic: 'Магический реализм',
  epistolary_fiction: 'Эпистолярная проза',
  prose_neformatny: 'Экспериментальная, неформатная проза',
  aphorisms: 'Афоризмы, цитаты',
  great_story: 'Роман, повесть',
  story: 'Малые литературные формы прозы: рассказы, эссе, новеллы, феерия',
  prose_abs: 'Фантасмагория, абсурдистская проза',
  love_contemporary: 'Современные любовные романы',
  love_history: 'Исторические любовные романы',
  love_detective: 'Остросюжетные любовные романы',
  love_short: 'Короткие любовные романы',
  love_erotica: 'Эротическая литература',
  love: 'Любовные романы',
  love_sf: 'Любовное фэнтези, любовно-фантастические романы',
  love_hard: 'Порно',
  adv_history: 'Исторические приключения',
  adv_indian: 'Вестерн, про индейцев',
  adv_maritime: 'Морские приключения',
  adv_geo: 'Путешествия и география',
  adv_animal: 'Природа и животные',
  adventure: 'Приключения',
  child_adv: 'Приключения для детей и подростков',
  adv_modern: 'Приключения в современном мире',
  tale_chivalry: 'Рыцарский роман',
  adv_story: 'Авантюрный роман',
  child_tale: 'Сказки народов мира',
  child_verse: 'Стихи для детей',
  child_prose: 'Проза для детей',
  child_sf: 'Фантастика для детей',
  child_det: 'Детская остросюжетная литература',
  child_education: 'Детская образовательная литература',
  children: 'Детская литература',
  child_classical: 'Классическая детская литература',
  child_tale_rus: 'Русские сказки',
  foreign_children: 'Зарубежная литература для детей',
  prose_game: 'Игры, упражнения для детей',
  religion_budda: 'Буддизм',
  sci_religion: 'Религиоведение',
  religion_esoterics: 'Эзотерика, эзотерическая литература',
  religion_self: 'Самосовершенствование',
  religion: 'Религия, религиозная литература',
  religion_christianity: 'Христианство',
  religion_orthodoxy: 'Православие',
  religion_protestantism: 'Протестантизм',
  religion_catholicism: 'Католицизм',
  religion_judaism: 'Иудаизм',
  religion_hinduism: 'Индуизм',
  religion_islam: 'Ислам',
  religion_paganism: 'Язычество',
  astrology: 'Астрология и хиромантия',
  poetry: 'Поэзия',
  humor_verse: 'Юмористические стихи, басни',
  poetry_classical: 'Классическая поэзия',
  poetry_modern: 'Современная поэзия',
  poetry_rus_classical: 'Классическая русская поэзия',
  poetry_rus_modern: 'Современная русская поэзия',
  poetry_for_classical: 'Классическая зарубежная поэзия',
  poetry_for_modern: 'Современная зарубежная поэзия',
  poetry_east: 'Поэзия Востока',
  lyrics: 'Лирика',
  song_poetry: 'Песенная поэзия',
  poem: 'Поэма, эпическая поэзия',
  palindromes: 'Визуальная и экспериментальная поэзия, верлибры, палиндромы',
  dramaturgy: 'Драматургия',
  comedy: 'Комедия',
  tragedy: 'Трагедия',
  drama: 'Драма',
  drama_antique: 'Античная драма',
  screenplays: 'Сценарий',
  vaudeville: 'Мистерия, буффонада, водевиль',
  antique_ant: 'Античная литература',
  antique_european: 'Европейская старинная литература',
  antique_russian: 'Древнерусская литература',
  antique_east: 'Древневосточная литература',
  antique: 'Старинная литература',
  antique_myths: 'Мифы. Легенды. Эпос',
  folklore: 'Фольклор, загадки',
  folk_tale: 'Народные сказки',
  epic: 'Былины, эпопея',
  proverbs: 'Пословицы, поговорки',
  folk_songs: 'Народные песни',
  child_folklore: 'Детский фольклор',
  limerick: 'Частушки, прибаутки, потешки',
  sci_history: 'История',
  sci_psychology: 'Психология и психотерапия',
  sci_philosophy: 'Философия',
  sci_politics: 'Политика',
  sci_juris: 'Юриспруденция',
  sci_linguistic: 'Языкознание, иностранные языки',
  sci_medicine: 'Медицина',
  sci_phys: 'Физика',
  sci_math: 'Математика',
  sci_chem: 'Химия',
  sci_biology: 'Биология, биофизика, биохимия',
  science: 'Научная литература',
  sci_cosmos: 'Астрономия и Космос',
  sci_geo: 'Геология и география',
  sci_state: 'Государство и право',
  sci_economy: 'Экономика',
  sci_medicine_alternative: 'Альтернативная медицина',
  sci_philology: 'Литературоведение',
  sci_popular: 'Зарубежная образовательная литература, зарубежная прикладная, научно-популярная литература',
  military_history: 'Военная история',
  sci_social_studies: 'Обществознание, социология',
  sci_zoo: 'Зоология',
  sci_botany: 'Ботаника',
  sci_ecology: 'Экология',
  sci_oriental: 'Востоковедение',
  sci_theories: 'Альтернативные науки и научные теории',
  sci_veterinary: 'Ветеринария',
  sci_culture: 'Культурология',
  notes: 'Партитуры',
  nonf_criticism: 'Критика',
  design: 'Искусство и Дизайн',
  music: 'Музыка',
  painting: 'Живопись, альбомы, иллюстрированные каталоги',
  architecture_book: 'Скульптура и архитектура',
  art_world_culture: 'Мировая художественная культура',
  cine: 'Кино',
  theatre: 'Театр',
  art_criticism: 'Искусствоведение',
  sci_tech: 'Технические науки',
  sci_build: 'Строительство и сопромат',
  sci_radio: 'Радиоэлектроника',
  sci_metal: 'Металлургия',
  sci_transport: 'Транспорт и авиация',
  military_weapon: 'Военное дело, военная техника и вооружение',
  auto_business: 'Автодело',
  equ_history: 'История техники',
  comp_www: 'ОС и Сети, интернет',
  comp_hard: 'Компьютерное железо и цифровая обработка сигналов',
  comp_db: 'Программирование, программы, базы данных',
  computers: 'Зарубежная компьютерная литература',
  tbg_computers: 'Учебные пособия, самоучители',
  ref_encyc: 'Энциклопедии',
  ref_dict: 'Словари',
  ref_ref: 'Справочники',
  ref_guide: 'Руководства',
  reference: 'Справочная литература',
  geo_guides: 'Путеводители, карты, атласы',
  nonf_biography: 'Биографии и Мемуары',
  nonf_publicism: 'Публицистика',
  nonfiction: 'Документальная литература',
  nonf_military: 'Военная документалистика и аналитика',
  military_special: 'Военное дело',
  travel_notes: 'География, путевые заметки',
  humor_anecdote: 'Анекдоты',
  humor_prose: 'Юмористическая проза',
  humor: 'Юмор',
  humor_satire: 'Сатира',
  home_cooking: 'Кулинария',
  home_pets: 'Домашние животные',
  home_crafts: 'Хобби и ремесла',
  home_entertain: 'Развлечения',
  home_health: 'Здоровье',
  home_garden: 'Сад и огород',
  home_diy: 'Сделай сам',
  home_sport: 'Боевые искусства, спорт',
  home_sex: 'Семейные отношения, секс',
  home: 'Домоводство',
  sci_pedagogy: 'Педагогика, воспитание детей, литература для родителей',
  auto_regulations: 'Автомобили и ПДД',
  home_collecting: 'Коллекционирование',
  family: 'Семейные отношения',
  other: 'Неотсортированное',
  periodic: 'Журналы, газеты',
  comics: 'Комиксы',
  unfinished: 'Незавершенное',
  fanfiction: 'Фанфик',
  network_literature: 'Самиздат, сетевая литература',
  banking: 'Финансы',
  org_behavior: 'Маркетинг, PR',
  popular_business: 'Карьера, кадры',
  economics_ref: 'Деловая литература',
  economics: 'Экономика',
  sci_textbook: 'Учебники и пособия',
  tbg_school: 'Школьные учебники и пособия, рефераты, шпаргалки',
  tbg_secondary: 'Учебники и пособия для среднего и специального образования',
  tbg_higher: 'Учебники и пособия ВУЗов',

  // ── Алиасы и новые жанры (freeLib genre.tsv) ──
  // Фантастика
  sf_writing: 'Научная фантастика',
  sf_su: 'Научная фантастика',
  foreign_fantasy: 'Фэнтези',
  everyday_fantasy: 'Фэнтези',
  asian_fantasy: 'Фэнтези',
  dark_fantasy: 'Тёмное фэнтези',
  sf_space_opera: 'Космическая фантастика',
  fantasy_det: 'Детективная фантастика',
  city_fantasy: 'Городское фэнтези',
  popadanec: 'Попаданцы',
  sf_all: 'Фантастика',
  adventure_fantasy: 'Фантастика',
  foreign_sf: 'Зарубежная фантастика',
  sf_industrial_magic: 'Фантастика',
  slavic_fantasy: 'Славянское фэнтези',
  fantasy_alt_hist: 'Альтернативная история',
  nsf: 'Ненаучная фантастика',
  sf_fantasy_irony: 'Ироническое фэнтези',
  sf_irony: 'Ироническая фантастика',
  historical_fantasy: 'Историческое фэнтези',
  humor_fantasy: 'Юмористическое фэнтези',
  utopia: 'Утопия',
  dystopian: 'Антиутопия',
  dorama: 'Дорама',
  boyar_anime: 'Боярское аниме',
  magic_school: 'Магическая академия',
  sf_realrpg: 'РеалРПГ',
  // Проза
  short_story: 'Рассказ',
  roman: 'Роман',
  essay: 'Эссе, очерк, этюд, набросок',
  dissident: 'Антисоветская литература',
  sagas: 'Семейный роман, семейная сага',
  prose_sentimental: 'Сентиментальная проза',
  prose_epic: 'Эпопея',
  extravaganza: 'Феерия',
  prose_all: 'Проза',
  // Детективы
  det_all: 'Детективы',
  det_artifact: 'Детективы',
  det_other: 'Детективы',
  thriller_mystery: 'Триллер',
  det_cozy: 'Дамский детективный роман',
  det_lady: 'Дамский детективный роман',
  thriller_legal: 'Юридический триллер',
  thriller_medical: 'Медицинский триллер',
  thriller_techno: 'Техно-триллер',
  thriller_psychology: 'Психологический триллер',
  // Наука
  sci_psychology_popular: 'Психология',
  tech_all: 'Технические науки',
  sci_all: 'Научная литература',
  sci_business: 'Деловая литература',
  sci_crib: 'Шпаргалки',
  foreign_language: 'Иностранные языки',
  sci_biochem: 'Биохимия',
  psy_childs: 'Детская психология',
  sci_physchem: 'Физическая химия',
  psy_sex_and_family: 'Секс и семейная психология',
  psy_theraphy: 'Психотерапия и консультирование',
  sci_biophys: 'Биофизика',
  sci_orgchem: 'Органическая химия',
  sci_anachem: 'Аналитическая химия',
  sci_abstract: 'Рефераты',
  // Документальная
  nonf_all: 'Документальная литература',
  nonf_biography_writers: 'Биографии и Мемуары',
  nonf_biography_celebrities: 'Биографии и Мемуары',
  nonf_biography_historical: 'Биографии и Мемуары',
  about_musicians: 'Биографии и Мемуары',
  nonf_biography_military_figures: 'Военная документалистика',
  // Любовные романы
  love_all: 'Любовные романы',
  love_fantasy: 'Любовная фантастика',
  // Детское
  child_all: 'Детская литература',
  child_dramaturgy: 'Детская литература',
  child_prose_history: 'Детская литература',
  child_prose_humor: 'Проза для детей',
  child_prose_romantic: 'Проза для детей',
  child_adv_animal: 'Детские приключения',
  child_det_children_detectives: 'Детские детективы',
  child_det_other: 'Детские детективы',
  child_det_animal_detectives: 'Детские детективы',
  ya: 'Подростковая литература',
  child_tale_russian_writers: 'Русские сказки',
  child_tale_foreign_writers: 'Зарубежная литература для детей',
  child_sf_space: 'Детская фантастика',
  child_sf_hronoopera: 'Детская фантастика',
  child_sf_horror: 'Детская фантастика',
  child_sf_fantasy: 'Детская фантастика',
  // Домоводство
  home_all: 'Домоводство',
  // Религия
  religion_rel: 'Религия',
  religion_all: 'Религия',
  palmistry: 'Хиромантия',
  // Приключения
  adv_all: 'Приключения',
  adv_western: 'Вестерн',
  // Прочее
  other_all: 'Неотсортированное',
  diafilm: 'Диафильмы',
  computer_translation: 'Машинный перевод',
  fan_translation: 'Любительский перевод',
  // Юмор
  humor_all: 'Юмор',
  // Поэзия и драматургия
  poetry_all: 'Поэзия',
  in_verse: 'В стихах',
  epic_poetry: 'Эпическая поэзия',
  fable: 'Басни',
  experimental_poetry: 'Экспериментальная поэзия',
  vers_libre: 'Верлибры',
  visual_poetry: 'Визуальная поэзия',
  dramaturgy_all: 'Драматургия',
  scenarios: 'Сценарии',
  mystery: 'Мистерия',
  // Справочники
  ref_all: 'Справочная литература',
  // Военное дело
  military_arts: 'Боевые искусства',
  military_all: 'Военное дело',
  military: 'Военное дело',
  // Компьютеры
  comp_all: 'Околокомпьютерная литература',
  comp_programming: 'Программирование',
  comp_osnet: 'ОС и Сети',
  comp_soft: 'Программы',
  comp_dsp: 'Цифровая обработка сигналов',
  // Старинное
  antique_all: 'Старинная литература',
  // Деловая литература
  marketing: 'Маркетинг, PR, реклама',
  management: 'Управление, подбор персонала',
  economics_all: 'Экономика',
  stock: 'Ценные бумаги, инвестиции',
  accounting: 'Бухучет и аудит',
  personal_finance: 'Личные финансы',
  job_hunting: 'Поиск работы, карьера',
  small_business: 'Малый бизнес',
  paper_work: 'Делопроизводство',
  industries: 'Отраслевые издания',
  real_estate: 'Недвижимость',
  global_economy: 'Внешняя торговля',
  trade: 'Торговля',
  // Фольклор
  folklore_all: 'Фольклор',
  riddles: 'Загадки',
  // Культура и искусство
  visual_arts: 'Изобразительное искусство, фотография',
  culture_all: 'Культура и искусство'
};

export function formatGenreLabel(value = '') {
  const raw = String(value || '').trim();
  if (!raw) {
    return '';
  }
  return GENRE_LABELS[raw] || raw;
}

/** Сырые коды жанров из поля книги (разделители как в .inpx) */
export function parseGenreCodes(value = '') {
  return String(value || '')
    .split(/[:,;]/)
    .map((item) => item.trim())
    .filter(Boolean);
}

export function formatGenreList(value = '') {
  return parseGenreCodes(value).map((code) => formatGenreLabel(code));
}

export function formatAuthorLabel(value = '') {
  const raw = String(value || '').trim();
  if (!raw) {
    return '';
  }
  const authors = raw
    .split(':')
    .map((author) => author.split(',').map((part) => part.trim()).filter(Boolean).join(' '))
    .filter(Boolean);
  if (!authors.length) {
    return raw;
  }
  return authors.slice(0, 3).join(', ') + (authors.length > 3 ? ` и ещё ${authors.length - 3}` : '');
}

export function formatLanguageLabel(value = '') {
  const raw = String(value || '').trim();
  if (!raw || raw === 'unknown') {
    return 'Не указан';
  }
  return raw.toUpperCase();
}

export { GENRE_LABELS };

const GENRE_GROUPS = {
  'Фантастика': ['sf_history','sf_action','sf_epic','sf_heroic','sf_detective','sf_cyberpunk','sf_space','sf_social','sf_horror','sf_humor','sf_fantasy','sf','sf_fantasy_city','sf_postapocalyptic','sf_litrpg','sf_etc','russian_fantasy','sf_technofantasy','fairy_fantasy','hronoopera','sf_mystic','sf_stimpank','modern_tale','popadancy','sf_writing','sf_su','foreign_fantasy','everyday_fantasy','asian_fantasy','dark_fantasy','sf_space_opera','fantasy_det','city_fantasy','popadanec','sf_all','adventure_fantasy','foreign_sf','sf_industrial_magic','slavic_fantasy','fantasy_alt_hist','nsf','sf_fantasy_irony','sf_irony','historical_fantasy','humor_fantasy','utopia','dystopian','dorama','boyar_anime','magic_school','sf_realrpg'],
  'Детективы': ['det_classic','det_police','det_action','det_irony','det_history','det_espionage','det_crime','det_political','det_maniac','det_hard','thriller','detective','det_su','det_all','det_artifact','det_other','thriller_mystery','det_cozy','det_lady','thriller_legal','thriller_medical','thriller_techno','thriller_psychology'],
  'Проза': ['prose','prose_classic','prose_history','prose_contemporary','prose_counter','prose_rus_classic','prose_su_classics','prose_military','foreign_prose','foreign_antique','literature_18','literature_19','literature_20','gothic_novel','prose_magic','epistolary_fiction','prose_neformatny','aphorisms','great_story','story','prose_abs','short_story','roman','essay','dissident','sagas','prose_sentimental','prose_epic','extravaganza','prose_all'],
  'Любовные романы': ['love_contemporary','love_history','love_detective','love_short','love_erotica','love','love_sf','love_hard','love_all','love_fantasy'],
  'Приключения': ['adv_history','adv_indian','adv_maritime','adv_geo','adv_animal','adventure','child_adv','adv_modern','tale_chivalry','adv_story','adv_all','adv_western','child_adv_animal'],
  'Детская литература': ['child_tale','child_verse','child_prose','child_sf','child_det','child_education','children','child_classical','child_tale_rus','foreign_children','prose_game','child_all','child_dramaturgy','child_prose_history','child_prose_humor','child_prose_romantic','child_det_children_detectives','child_det_other','child_det_animal_detectives','ya','child_tale_russian_writers','child_tale_foreign_writers','child_sf_space','child_sf_hronoopera','child_sf_horror','child_sf_fantasy'],
  'Религия и эзотерика': ['religion_budda','sci_religion','religion_esoterics','religion_self','religion','religion_christianity','religion_orthodoxy','religion_protestantism','religion_catholicism','religion_judaism','religion_hinduism','religion_islam','religion_paganism','astrology','religion_rel','religion_all','palmistry'],
  'Поэзия и драматургия': ['poetry','humor_verse','poetry_classical','poetry_modern','poetry_rus_classical','poetry_rus_modern','poetry_for_classical','poetry_for_modern','poetry_east','lyrics','song_poetry','poem','palindromes','dramaturgy','comedy','tragedy','drama','drama_antique','screenplays','vaudeville','poetry_all','in_verse','epic_poetry','fable','experimental_poetry','vers_libre','visual_poetry','dramaturgy_all','scenarios','mystery'],
  'Старинная литература': ['antique_ant','antique_european','antique_russian','antique_east','antique','antique_myths','antique_all'],
  'Фольклор': ['folklore','folk_tale','epic','proverbs','folk_songs','child_folklore','limerick','folklore_all','riddles'],
  'Наука': ['sci_history','sci_psychology','sci_philosophy','sci_politics','sci_juris','sci_linguistic','sci_medicine','sci_phys','sci_math','sci_chem','sci_biology','science','sci_cosmos','sci_geo','sci_state','sci_economy','sci_medicine_alternative','sci_philology','sci_popular','military_history','sci_social_studies','sci_zoo','sci_botany','sci_ecology','sci_oriental','sci_theories','sci_veterinary','sci_culture','sci_psychology_popular','tech_all','sci_all','sci_business','sci_crib','foreign_language','sci_biochem','psy_childs','sci_physchem','psy_sex_and_family','psy_theraphy','sci_biophys','sci_orgchem','sci_anachem','sci_abstract'],
  'Искусство': ['notes','nonf_criticism','design','music','painting','architecture_book','art_world_culture','cine','theatre','art_criticism','visual_arts','culture_all'],
  'Техника': ['sci_tech','sci_build','sci_radio','sci_metal','sci_transport','auto_business','equ_history'],
  'Военное дело': ['military_weapon','military_special','military_arts','military_all','military'],
  'Компьютеры': ['comp_www','comp_hard','comp_db','computers','tbg_computers','comp_all','comp_programming','comp_osnet','comp_soft','comp_dsp'],
  'Справочники': ['ref_encyc','ref_dict','ref_ref','ref_guide','reference','geo_guides','ref_all'],
  'Документальная': ['nonf_biography','nonf_publicism','nonfiction','nonf_military','travel_notes','nonf_all','nonf_biography_writers','nonf_biography_celebrities','nonf_biography_historical','about_musicians','nonf_biography_military_figures'],
  'Юмор': ['humor_anecdote','humor_prose','humor','humor_satire','humor_all'],
  'Дом и быт': ['home_cooking','home_pets','home_crafts','home_entertain','home_health','home_garden','home_diy','home_sport','home_sex','home','sci_pedagogy','auto_regulations','home_collecting','family','home_all'],
  'Прочее': ['other','periodic','comics','unfinished','fanfiction','network_literature','other_all','diafilm','computer_translation','fan_translation'],
  'Бизнес': ['banking','org_behavior','popular_business','economics_ref','economics','marketing','management','economics_all','stock','accounting','personal_finance','job_hunting','small_business','paper_work','industries','real_estate','global_economy','trade'],
  'Учебники': ['sci_textbook','tbg_school','tbg_secondary','tbg_higher']
};

// Reverse index: genre code → group name
const GENRE_TO_GROUP = {};
for (const [group, codes] of Object.entries(GENRE_GROUPS)) {
  for (const code of codes) {
    GENRE_TO_GROUP[code] = group;
  }
}

export function getGenreGroup(code) {
  return GENRE_TO_GROUP[code] || null;
}

export function getGenreGroups() {
  return GENRE_GROUPS;
}

export { GENRE_TO_GROUP };
